version: '3.7'
services:
  postgres:
    container_name: postgres
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: task_manager_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    tmpfs: /tmp
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"